import { addDays, addMonths, format, subDays } from "date-fns";
import type {
  AppUser,
  Issue,
  IssueRequest,
  Item,
  Member,
} from "./types";
import { makeSerial } from "./code";

const iso = (d: Date) => format(d, "yyyy-MM-dd");
const today = new Date();

export const seedItems: Item[] = [
  {
    id: makeSerial("Science", "book", 1),
    kind: "book",
    name: "A Brief History of Time",
    author: "Stephen Hawking",
    category: "Science",
    serialNo: makeSerial("Science", "book", 1),
    status: "Available",
    cost: 499,
    procurementDate: iso(subDays(today, 365)),
    quantity: 1,
  },
  {
    id: makeSerial("Science", "book", 2),
    kind: "book",
    name: "The Selfish Gene",
    author: "Richard Dawkins",
    category: "Science",
    serialNo: makeSerial("Science", "book", 2),
    status: "Available",
    cost: 399,
    procurementDate: iso(subDays(today, 300)),
    quantity: 1,
  },
  {
    id: makeSerial("Economics", "book", 1),
    kind: "book",
    name: "Freakonomics",
    author: "Steven Levitt",
    category: "Economics",
    serialNo: makeSerial("Economics", "book", 1),
    status: "Available",
    cost: 350,
    procurementDate: iso(subDays(today, 200)),
    quantity: 1,
  },
  {
    id: makeSerial("Fiction", "book", 1),
    kind: "book",
    name: "1984",
    author: "George Orwell",
    category: "Fiction",
    serialNo: makeSerial("Fiction", "book", 1),
    status: "Available",
    cost: 299,
    procurementDate: iso(subDays(today, 100)),
    quantity: 1,
  },
  {
    id: makeSerial("Fiction", "book", 2),
    kind: "book",
    name: "To Kill a Mockingbird",
    author: "Harper Lee",
    category: "Fiction",
    serialNo: makeSerial("Fiction", "book", 2),
    status: "Unavailable",
    cost: 320,
    procurementDate: iso(subDays(today, 150)),
    quantity: 1,
  },
  {
    id: makeSerial("Children", "book", 1),
    kind: "book",
    name: "Matilda",
    author: "Roald Dahl",
    category: "Children",
    serialNo: makeSerial("Children", "book", 1),
    status: "Available",
    cost: 250,
    procurementDate: iso(subDays(today, 75)),
    quantity: 1,
  },
  {
    id: makeSerial("Personal Development", "book", 1),
    kind: "book",
    name: "Atomic Habits",
    author: "James Clear",
    category: "Personal Development",
    serialNo: makeSerial("Personal Development", "book", 1),
    status: "Available",
    cost: 550,
    procurementDate: iso(subDays(today, 60)),
    quantity: 1,
  },
  {
    id: makeSerial("Fiction", "movie", 1),
    kind: "movie",
    name: "Inception",
    author: "Christopher Nolan",
    category: "Fiction",
    serialNo: makeSerial("Fiction", "movie", 1),
    status: "Available",
    cost: 250,
    procurementDate: iso(subDays(today, 90)),
    quantity: 1,
  },
  {
    id: makeSerial("Science", "movie", 1),
    kind: "movie",
    name: "Interstellar",
    author: "Christopher Nolan",
    category: "Science",
    serialNo: makeSerial("Science", "movie", 1),
    status: "Available",
    cost: 299,
    procurementDate: iso(subDays(today, 45)),
    quantity: 1,
  },
  {
    id: makeSerial("Children", "movie", 1),
    kind: "movie",
    name: "The Lion King",
    author: "Rob Minkoff",
    category: "Children",
    serialNo: makeSerial("Children", "movie", 1),
    status: "Available",
    cost: 199,
    procurementDate: iso(subDays(today, 30)),
    quantity: 1,
  },
];

export const seedMembers: Member[] = [
  {
    id: "M001",
    firstName: "Priya",
    lastName: "Sharma",
    contactNumber: "9876543210",
    contactAddress: "12 MG Road, Bangalore",
    aadhaar: "1234-5678-9012",
    startDate: iso(subDays(today, 30)),
    endDate: iso(addMonths(subDays(today, 30), 6)),
    duration: "6m",
    status: "Active",
    finePending: 0,
  },
  {
    id: "M002",
    firstName: "Arjun",
    lastName: "Nair",
    contactNumber: "9988776655",
    contactAddress: "45 Park Street, Kolkata",
    aadhaar: "9876-5432-1098",
    startDate: iso(subDays(today, 200)),
    endDate: iso(addMonths(subDays(today, 200), 12)),
    duration: "1y",
    status: "Active",
    finePending: 0,
  },
];

export const seedAppUsers: AppUser[] = [
  {
    id: "U-ADM",
    name: "Administrator",
    active: true,
    isAdmin: true,
    username: "adm",
    password: "adm",
  },
  {
    id: "U-USR",
    name: "Regular User",
    active: true,
    isAdmin: false,
    username: "user",
    password: "user",
  },
];

export const seedIssues: Issue[] = [
  {
    id: "I001",
    itemId: makeSerial("Fiction", "book", 2),
    serialNo: makeSerial("Fiction", "book", 2),
    memberId: "M001",
    issueDate: iso(subDays(today, 20)),
    returnDueDate: iso(addDays(subDays(today, 20), 15)),
    fineCalculated: 0,
    finePaid: false,
    status: "Active",
  },
];

export const seedRequests: IssueRequest[] = [
  {
    id: "R001",
    memberId: "M002",
    itemName: "The Lean Startup",
    requestedDate: iso(subDays(today, 10)),
  },
  {
    id: "R002",
    memberId: "M001",
    itemName: "Sapiens",
    requestedDate: iso(subDays(today, 5)),
    fulfilledDate: iso(subDays(today, 2)),
  },
];
